tracked-sites-csv-filename: targets.csv
output-data-dir: data/2020-06/
tracked-telegram-channels:
  - akhbartasnim
  - BestNoticias
  - BBCArabic
  - mehrinternational
  - BellumActa
  - ejtemaeitasnim
  - rtarabictelegram
  - DifusionIndependiente
  - khorasanisna
  - farsivoa
  - newschannelA
  - Isnakhouzestan
  - CNNpolitics
  - RealClearPolitics
  - isnahamedan
  - IRNA_MULTIMEDIA
  - mehragency
  - mehrkermanshah
  - akhbaralnilin
  - isna94
  - newsticker1
  - alertajudiada
  - rt_russian
  - irna_1313
  - LatestTechnologyNews
  - YidTel
  - Isnamarkazi
  - mehrsemnan
  - irnaalborz
  - isnaalborz1
  - mehrgolestan
  - linkresaneha
  - mehrfars
  - Tasnimnews
  - putosjudiosnews
  - tasnimnewslorstan
  - mehrhamedan
  - voiceofeurope
  - irna1934
  - newsbeast
  - wissenswertes1
  - mehrphoto
  - nasimqazvin
  - defendevropa
  - contraototalitarismodaonuenom
  - infowarslive
  - bazarekar_novin
  - nytimes
  - nytimes
  - mehrcinema
  - maraghehirna
  - politicamenteinformado
  - kanoonfarhangiyan
  - mod_gov_sy
  - mehrqom
  - rasadkhabar
  - AkhbarKhouz
  - ISNAMEDIA
  - noticiasul
  - goftvagobatabiat
  - mehrkordestan
  - xrrssfeed
  - Breitbart
  - EurasianNews
  - zananiran
  - rtnoticias
  - patriarcado
  - DieWahrheitnurdieWahrheit
  - InternationalRel
  - pol4chan
  - newsroom1
  - UnabhaengigerInfokanal
  - caspiankhabar
  - akh_malekan
  - NoticieroPolitico
  - Brexiteers
  - globalnewsgeopolitica
  - annack
  - bbcworldnews
  - bbcworldnews
  - ddbneuigkeiten
  - tasnimnewsfars
  - ak47_army
  - ganji_akbar
  - tajik57
  - Nieuwshoorn
  - eraikiz
  - irsteelreport
  - info288
  - Forwardnews
  - LibertyShill
  - youniversitycity
  - alianvarardabili
  - isnakhalijefars
  - AsianNewsNetwork
  - NSRINewsChannel
  - feminismos
  - antiilluminaten
  - r_nottheonion
  - irnagolestaan
  - karaulny
  - internationalLaw
  - Pilban_animation
  - presstv
  - randomanonch
  - randomanonch
  - DDHHSolidaridadAccionDirecta
  - Americaspolitics
  - FascistbookNewsAndMedia
  - UnityNewsNetwork
  - FarhangianNews1
  - persiangulfstudies
  - varzeshitasnim
  - politicalite
  - politicalite
  - TommyRobinsonNews
  - TommyRobinsonNews
  - Occidente
  - Radioarasbaran
  - golvaninews
  - simorghedalatnews
  - newspicker
  - washingtonpost
  - washingtonpost
  - STIPPLE78
  - WWWSNGOIR
  - lorvarzesh
  - pjwnews
  - pjwnews
  - PatriotNewz
  - football
  - mowlaverdi
  - LaEraMX
  - rasanetabesh
  - JewishNews
  - oliverjanich
  - CANALFeministaPodemita
  - GefaArgentina
  - Entreverao
  - nowdad_news
  - plumtv
  - fuckyouthatswhy
  - peyman00731
  - j_rcsgilan
  - eghtesadjournal
  - sarbedarane_ghadir
  - MARIOBORG20
  - UkraineNewsGeneral
  - doamuslims
  - ardabilnews
  - TheForBritainMovement
  - CryptoPanorama
  - Iranian_UK
  - tourism_handicruft_cultural
  - zaminonline
  - CIGtelegram
  - CIGtelegram
  - sedayepayeab1
  - hamawanews
  - mobintrade
  - raheslahat_ir
  - radicalagenda
  - farhikhteganedamghani
  - muinews
  - jamesgoddard89
  - mostlyiwrite
  - khabarenergy
  - goyimsES
  - newsbilesavar
  - canalfibradeherois
  - comuneras
  - bant4chan
  - tourismnews
  - AntifaAllstars
  - xoynews
  - unionsiriavenezuela
  - Instagrampap
  - F_S_C_P
  - rasatabib
  - Bankiha
  - yazdraport
  - Asreandisheh
  - flowercitymahallat
  - Thelibertyobserver
  - ettehad
  - krasniydom
  - mazahebnews
  - QlobalChangeUSA
  - womenstudies
  - kafeakhbar
  - tehranmc
  - Cuckistan
  - UniteTheRightUK
  - Geoestrategia1
  - khabbar_khan
  - PoliticalMemes
  - JohnHumanKind
  - yellowvest
  - Saeed_Kamali_Dehghan
  - dastanirani
  - rtintl
  - NGObehda
  - Info288_deportes
  - theresistanceengland
  - mediamediame
  - ghrr2004gmailcom
  - ch_envir_iran
  - tebsonnatiii
  - Irannkhabarrr
  - aminoroayayi
  - k_health
  - Thecelticempire
  - infowarsofficalchat
  - MiloOfficial
  - ForBritainMovementLondon
  - apolitical
  - InvestinginIran
  - DieForIsraelGoy
  - DieForIsraelGoy
  - stopthecensorship
  - stopthecensorship
  - InfoWarsChannel
  - datascientology
  - dast_neveshteha
  - modafe
  - maxrepost
  - Khaneyeketab
  - niemandswasser
  - smolny7
  - Porseshgar
  - klidar
  - wazsport
  - darvishnameh
  - Emam_Asheghan
  - HalaNews
  - RealNazbol
  - RealNazbol
  - mahak47
  - Zaminyar
  - europeanist
  - khouzestaniya
  - TITANSOFLIBERTY
  - behzad_samadi
  - hajjnews
  - mobinsb
  - newsparandpress
  - strategy110
  - nedayesalmas
  - toalibertarian
  - toalibertarian
  - Newsworthtelling1
  - culttture
  - SxRcat
  - QlobalChange
  - Leftygram
  - froughefarda
  - simorghedalat
  - tabanweekly
  - sargon_of_akkad
  - sargon_of_akkad
  - PendolaDorada
  - notizie
  - IRANNEGASHT
  - cienciaparatodos
  - thelittlelioness
  - Multiculturalizate
  - ardsport
  - notary_ir
  - gingersrant
  - PaulaPCay
  - bimecenter
  - SCSRT
  - AussiesUnited
  - booltannews
  - AradAnalysis
  - insurancenews
  - judiada
  - IranPistachioNet
  - khabarestan
  - sobheabadeh
  - kpf_kermanshah
  - movimientolaboralsindical
  - BigTwentyTwentyFeed
  - CanalREDCOM
  - Mountaineering_Club_of_Iran
  - shorakhabaresfahan
  - r_movies
  - barankavir
  - devonpatriotschannel
  - daftarnamayandemardom
  - madanakhbar
  - IsraelNoticias
  - AlexJonesChannel
  - kononenkome
  - DrMnegahban
  - randomredpills
  - addmeto
  - seyedjavadmiri
  - bidariymelat
  - Iran_puppet_theater
  - BellumActaNews
  - BellumActaNews
  - newspanopticon
  - JoopeANews
  - AliKianiRadAgrAppEcoInfo
  - ketabenaab
  - returnofthemark
  - taxpress
  - MUKALLANEWS
  - QlobalChangeItalia
  - circuloveganopodemos
  - Sanctions_Inspector
  - ammarpress
  - whodareswins2
  - beadymanor
  - beadymanor
  - Tehranonline_Ir
  - WomenDemands
  - Farhangimsrt
  - mccima
  - razavieduu
  - organicinputs
  - GOORANTALEGHAN
  - Digital_Monkey_Business
  - kultur
  - zohour12
  - gaiabrasil
  - goodmorningkarl
  - EsXrebellion
  - hizbollahsyber
  - komajangal
  - BritainFirst
  - BritainFirst
  - newSpeaks
  - pezeshkanghanon
  - GholamrezaMohammadi
  - rozshomareadabi
  - paksazanfars
  - IslamMemes
  - IslamMemes
  - kermanshahmet
  - astaranews
  - XhDen
  - tasnimnewsgolestan
  - Altnewsnetwork
  - Altnewsnetwork
  - roopab
  - mtngo_ir
  - resistenciae
  - Jaydafransensupporters
  - nickmon1112
  - alzaymer_channel
  - WaterClinic
  - itganews
  - iran_science
  - AviYeminiOfficial
  - AviYeminiOfficial
  - PressTVFarsi
  - Iritfir
  - aamout
  - wakeywakeyworld
  - Trading_Group
  - wateriran
  - webdaarak
  - salmasnews
  - hccim
  - oitahlil
  - churchiil
  - jhaghshenas
  - ahkiran
  - contrainfo
  - milinfolive
  - nodal_geomatic
  - MovPirata
  - PiratasORG
  - rufabula
  - bijar
  - salam_ardostan
  - nomoremosques
  - yachting
  - massoumehebtekar
  - thegreatunsaid
  - podemosnoalttip
  - aradmanpub
  - Iranpainters
  - iranboom_ir
  - www_ccsi_ir
  - join_PLATT_FORM_now
  - ia_steklomoy
  - realjenloh
  - chinaposter
  - tabloelanatevokala
  - PatriotsAllianceUK
  - abdollahshahbazi
  - bamardum
  - PedramAstani
  - JackDawkins
  - ztgaorg
  - EmergingInfDis
  - armanhay_enghelab
  - khanehmellat133
  - sportyoungnews
  - tadbirekariman
  - a_hakimipour
  - yamanyoon
  - PatriotasConservadores
  - BreadPilled
  - redzion
  - ammar_enghelab
  - khabarnamehonline
  - naft24
  - yaremoud
  - suggestivem
  - irannewspaper
  - photoreport
  - Newsyemen2015
  - aminavidbc
  - studentrights
  - Mofyaz
  - PressGuard
  - hitl999
  - shadow_policy
  - babakborzouy
  - shirintanz
  - akhbarejam
  - Chadistan
  - basededucation
  - go338
  - prtargentina
  - LauraLoomerFanClub
  - HKAllInOne
  - HistoriayArqueologia
  - tooreel5me
  - geopoliticacr
  - daze_pol
  - mayameynews
  - Photoqomnews
  - EyeOnAntisemitism
  - WhiteIsRight
  - Owen_Shroyer
  - Olegsto
  - iycsardebil
  - Mobilearena_ua
  - irannaturalresources
  - Arsenal
  - payeshemohitzist
  - mahmoudabad1
  - kordkuy
  - techsparks
  - MilitaryMissileArticlesBooksMMAB
  - ArazAhar
  - sahandiranmehr
  - NazBol
  - NazBol
  - nicstavrogin
  - irfilmnews
  - mohitzistiha
  - me_metals
  - pilacuchu
  - Partisan2015
  - sciencedaily
  - VahidOnline
  - ICT_TechBiz_Inc
  - newsjahrom
  - sobhesahand
  - tayebeh_siavashi
  - Nahid_Tajedin
  - Xpoemx
  - mmrus
  - cryptomaymay
  - reflex_volucion
  - negahnews
  - margaritasimonyan
  - faranegar
  - sedaye_aab
  - AnahitaKangavarCampaign
  - hk_intl
  - islamictrends
  - IranianPhysicians
  - hamiantadbir
  - israelwc
  - infoschleuder
  - SomosSindicalistasCAT
  - wim4u
  - azadivasazandegi
  - didebane_enghelab
  - Drjalilrahimi
  - economiafeminita
  - homauondarabi
  - docpro
  - tuseah
  - ThirdWayFashposting
  - ThirdWayFashposting
  - thedailyprophet
  - jangaavaran
  - scientifically
  - iica_ir
  - TheConservativeArsenal
  - shitcommunistssay
  - EnvironmentFriends
  - rsssNGO
  - khat57
  - rooznamekhabar
  - GharaareSabz
  - Maneimshahrim
  - kanal3A
  - AnSoo
  - blogsostenible
  - ardabilfarda
  - cringanarchy
  - cringanarchy
  - alexmakus
  - zavtracast
  - holmogortalks
  - otaaghe_khabar
  - taqribnews
  - rezazade
  - tradinginoman
  - iranianhemophilia
  - ruidad
  - ChrisDoyle
  - jilwan_kurdistan
  - sgmeme
  - teory_elit
  - Fars_today
  - etedall
  - iranianhht
  - MBNews_UK
  - Ane_Bald
  - dailyredpill
  - r_latestagecapitalism
  - luiscarlosdiaz
  - andishkadeamoozesh
  - ali_kazami
  - khanehshahryaranjavan
  - JacobAWohl
  - cienciatecnologia
  - pourdastmalchi
  - naghdehall
  - motiv8britainnews
  - motiv8britainnews
  - bestimeline
  - andishefarhangsara
  - FolkRight
  - lovegulag
  - bestdrivers
  - gorgandoostan2
  - golestanrcs
  - siasimashhad
  - freevekalat
  - golpa20
  - newsrgb
  - reddit_android
  - info288_seguimientos
  - vatfor
  - iKiosk
  - iraniantunelingassociation
  - naserinejad
  - StopDomesticViolence
  - SIL0VIKI
  - ltms96
  - hezbeslamikar
  - dezhamkar
  - PayeshwestDOE
  - nedaykerman
  - proudboysbritannia
  - TheBEASTro
  - revayat_nashr_news
  - tuskanews
  - Earth_Earthquakes
  - loomeredofficial
  - loomeredofficial
  - conscienciacolectivacanal
  - militarymaps
  - iranrelief
  - safecommunityassociation
  - isgp_ir
  - shomareshmakooszohor
  - atabahrami
  - hamedanestan
  - hormozgan_sociology
  - ahmadmazani
  - gozaaaaaresh
  - Shahshahani14
  - BelicaS_contraInformacion
  - economistfarsi
  - SSAFUM
  - mohsen_mehralizadeh
  - qasreshiriin
  - Taleghaniha
  - qasreshiriin
  - TraditionalBritainGroup
  - BrasilSurreal
  - politsputnik
  - khabgard
  - ayatollahimani
  - MAminGhaneirad
  - mohandeszarabadi
  - sport_iau
  - sarzaminjavid
  - ahorageography
  - kashinguru
  - brodetsky
  - Kulturstudio
  - DemokratieInWuerde
  - AndalucialaqueMaS
  - dikultpohod
  - boomgardan
  - bookcitycc
  - bazaartheater
  - RedDog71Media
  - genderfluidhelisexual
  - golestanema1
  - jamiatdefaa
  - Haft_tv3
  - syriaalternativesnews
  - Internationallaw1
  - NosotrasNoSomosVasijas
  - didehban_ir
  - ansagram
  - worldnews_dormant
  - aillf
  - Dialysis
  - etehadsabzngo
  - tadbiroomidd
  - GhararGahShayeat
  - raahak
  - cienciatelegram
  - MuyFan36
  - majlismonitor
  - nejatdehande
  - khabartanz
  - IndianAtheist
  - KontraInfo
  - omar_alfarok105
  - eghtesadmashhad
  - balutbananzagros
  - bloghoseini
  - uni_urumia
  - hamidrezaei2
  - InSvensWelt
  - dddjournalism
  - ekotaa
  - rahmatollah_bigdeli
  - judenpresse_archive
  - Redes7
  - MAYDNR
  - ofoghroydad
  - ravanshadnia
  - Farhangemuze
  - iranathletics
  - nedaye_siyasat
  - skvir
  - CatloafNews
  - russianfuture
  - ISCCchannel
  - darshahrkhoy
  - prokhozhij
  - SCMEDIA
  - ArmanTadbir
  - khoyeslahat
  - proudboysusa
  - proudboysusa
  - GlennTeale
  - pestelnareywe
  - DazibaoDacibao
  - petexp
  - SeguridadInformatica
  - TegnoCienciaOmega
  - wearethearsenal
  - dabirkhanetose
  - varzeshmashhad
  - entehaj_news
  - BabolShahreBaharNarenj
  - havadarsorkh
  - gri_qscvfe
  - PNRW18
  - daokedao
  - sudakovss
  - bellacatena
  - sahatzist
  - modafean_enghlab
  - newsgula
  - fosau
  - pol_4chan
  - pol_4chan
  - gossluga
  - aatechnology
  - DerechodelaRed
  - samanehteshami
  - vorchunmedia
  - Akhbarmashhad
  - InoqTelegram
  - marxismct
  - marcogtv
  - gay_trans_agenda
  - gay_trans_agenda
  - azarmansouri
  - breadinc
  - freeleft
  - SolovievLive
  - zaminshenasan
  - azadunishahrood
  - zanan_emrooz
  - shahedakhell
  - Paperandboard
  - hatef_news
  - solhezibaschannel
  - E_B_M_I
  - nonblockchain
  - bookninja
  - futures_market
  - cosasdemimundo
  - QIdentity
  - deftiges
  - Avant_literature_Art
  - Pazshahr
  - iueatelegram
  - mohandesanseakhteman
  - bidarzani
  - SolarPunk
  - PersianNiknews
  - islamicnatsoc
  - baixacultura
  - hafez_brokerage
  - ekvinokurova
  - lond0ngrad
  - adhwaacentre
  - Ajiilll
  - irafta
  - dannytommo
  - Awarenessdaily
  - themedia
  - nada_com_nada
  - metacommunism
  - dronesrussia
  - Badsarparast
  - mashhadnews2015
  - great_and_sovereign
  - freedomspeach
  - paniranist_party
  - dplatonova
  - C4Memes
  - ProudlyPointless
  - Yidnews
  - PolitBulka
  - hkhezli
  - geopolitics_news
  - prosmis
  - hamiorg
  - tehran_oat
  - mamlekate
  - yellowvestsuk
  - nicanews
  - zaminemehr
  - dailyworld
  - dobare_azadi
  - irbicofficial
  - IranEnergynews
  - jebhe_mostazafin
  - khabarkoshti
  - ShitLiberalsSay
  - Daves_channel
  - the_guardian_news
  - iranesth
  - fararasane
  - mariwankhabar
  - yavaranzamin
  - GrimJohnoTheReaper
  - FamiliesDestroyedByTheState
  - JuliaJulsFrauenbuendnisKandel
  - nationalewochenschau
  - IlcasoScafroglia
  - islamic_model
  - khorsandy_pub
  - iranianlls
  - jangalaneh
  - drtorki
  - parvanemafichanel
  - naftoenergy
  - bogubreakingnews
  - BusinessNewsToday
  - artalevich
  - ebanistika
  - ZaragozaCNT
  - QAnons_Channel_Germany
  - Formoolyek
  - jadehiran
  - UrbanManagem
  - bisetoon_ksh
  - caspian24
  - farhangi_e_kian
  - AntifaPublicWatch
  - DissidentGreenDragon
  - Mariposas_Elitistas
  - Uncle_Paul1488
  - Uncle_Paul1488
  - smashculturalmarxism1
  - mesle_ammar
  - anarcos
  - shafieikia
  - sashakots
  - abyayalalaotrahistoria
  - gedgard
  - KhiyalKham
  - wikitransport
  - simayemehr
  - payameasalooye
  - salamttoseakhaeyren
  - sheidaei95
  - eco_press
  - sahmashena
  - semnaniau
  - khamgeyahkhari
  - onionchannel
  - INFOWARS_AMERICA
  - internet9000
  - Heath_Ledger_media
  - akhalaji
  - zhandarmeri
  - EconomicAndPoliticalNews
  - ensafnews
  - dar1negahksh
  - Virtualmedia_abfa
  - ebarez
  - matikandastan
  - music6234
  - dscampaign
  - MojtabaHeydari_ir
  - BloodAndHonour
  - BloodAndHonour
  - Canis_Channel
  - kbrvdvkr
  - spiritualscience
  - zerohedge
  - rlnfm
  - Dar_Astane_Bolouq
  - orange_channel
  - Montazeran_ir
  - w20to
  - ayandeyesabz
  - Khemess
  - rayehe313
  - bimeiranfars
  - MohitzistArasbaran
  - videomu
  - nezamrasht
  - nehzatsabzzagros
  - salesandbuy3
  - defence_news
  - tiat1
  - HonarPooya
  - ancapistantm
  - QuinceM
  - Academy_of_art
  - digamos
  - MicrobiologyNews
  - saludestatalpodemos
  - sinelor
  - siasate_eslami
  - iran_geomatics
  - BavarBaran
  - IRANBOARD
  - bayan_news
  - drahmadinejad
  - khatamonline
  - znfarhangi
  - ArdNeda
  - irautismorg
  - Achmaz
  - ukrnastup
  - faramoshkhaneh
  - Nevrotique
  - ATAnews
  - ketabegilan
  - ClintonFoundation
  - aslnoozdah
  - IFPhs
  - random2ch
  - iarexru
  - gorganiauu
  - kshdevelopment
  - ghanoondaily
  - ramsarnovin
  - mukhtarhashemi
  - khosropanah_ir
  - farhangmashhad
  - hananeh_ir
  - Bioethicsandhumanrights
  - canalhansulrichrudel
  - SmokesAndMemes
  - SmokesAndMemes
  - deathtonwo
  - solarstorm
  - white_genocide
  - white_genocide
  - FeministokAhaldugu
  - MCMLXXXIVwasbetter
  - conlasaludnosejuega
  - whitehousewatch
  - kaveh_farhadi
  - ahleTehranam
  - imamalisociety
  - irdiplomacy_ir
  - EsfandiarKhodaee
  - ahmadalireza_beigi
  - Ulsterpatriots
  - ProudboysPDX
  - electionallawyers
  - katehon_kyiv
  - irannc
  - randaoBR
  - weshallovercomb
  - Nohoomeday
  - dronenews
  - narcophobia
  - Ari_inchenin_shod_baradar
  - ciberseguridad
  - ciberseguridad
  - cinemahelal
  - guerrillaenredes
  - Iran_Telecom
  - parstodayrussian
  - AndaluciaPodemos
  - mohsen_sharifian
  - gre4ark
  - explaining
  - alvand_man
  - hakimUniversity
  - javadrooh
  - AIRWA
  - irangolfed
  - IranAmordadnews
  - gilan_ma
  - AltKnight
  - AltKnight
  - weedmeadow
  - apuntessnacionalistass
  - jomlekhabar
  - TweetsOfTrump
  - feminismosnafarroa
  - HabibSayyari
  - infursec
  - moloko_plus
  - change_the_world
  - breadlinks
  - wartrue
  - kolezev
  - eslahateiran
  - IranianGDA
  - khanefarhang94
  - niroonline
  - ieairan
  - guardiansofhongkong
  - lutzbachmann
  - lutzbachmann
  - EuropeLives
  - EuropeLives
  - thirdrailtalk
  - BenyaminFajr
  - ExpressZeitung
  - NicoReloadVision
  - offaofangeln
  - KotNaMirotvorze
  - wirsindvielmehr
  - SputnikMundo
  - MedvedevVesti
  - vseyxyeli
  - moballeghi
  - farhangiannews
  - Ayazastro
  - theaternews
  - tahlyleejtemaaey
  - naslenoir
  - kazemnasabalbaji
  - qazvinbar
  - Liamwalsall
  - CoinDesk
  - police_frequency
  - LegioChristi
  - sombreroblanco
  - tabrizlinks
  - SergeyKolyasnikov
  - ehsanname
  - IranGSI
  - spwsc
  - zanjandili
  - khawater_11
  - Reza_Qasempour
  - NewHasanMohaddesi
  - urmia_municipality
  - Shakheh_nabat
  - rouznameh
  - TheRealHouse
  - AssadStash
  - gypsycrusader
  - The_Library_II
  - mrboneswildride
  - indygram
  - doshanbe